" Setup Gvim specific settings
set lines=58
set columns=120

" Remove macvim toolbar
set go-=T

" Colours
color railscasts

" Alternatively go with a dark background
"set bg=dark
"if &background == "dark"
"    hi normal guibg=black
"    set transp=8
"endif

