"
" Ray Grasso's vim settings built up over a number of years from a variety of sources
"

set history=100
set undolevels=3000

set hlsearch " Highlight search terms
set smartcase " Ignore case when search term is all lower case

set nostartofline " Keep cursor at indent level on new line

set isk+=_,$,@,%,#,- " None of these should be word dividers, so make them not be
set ffs=unix,dos,mac " Support all three, in this order

set ruler " Always show current positions along the bottom 
set cmdheight=1 " The command bar is 2 high
set backspace=2 " Make backspace work normally

set shortmess=atI " Shortens messages to avoid 'press a key' prompt
set noerrorbells " Don't make noise
set novisualbell " Don't blink

set showmatch " Show matching brackets
set mat=3 " How many tenths of a second to blink matching brackets for

" Output some interesting info on the status line
set statusline=%F%m%r%h%w\ [FMT=%{&ff}]\ [TYPE=%Y]\ [POS=%04l,%04v][%p%%]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [LEN=%L]
set laststatus=2 " always show the status line

if has("syntax")
   syntax on
endif

set autoindent " Match our indent on a new line
set smartindent " Will indent automatically on braces and cinwords

" Unify out tab stops
set tabstop=4 " Tab spacing (settings below are just to unify it)
set softtabstop=4
set shiftwidth=4 

set expandtab " give me spaces please!
set smarttab

"set nowrap " do not wrap lines  

filetype plugin on " Ensure file type detection is on

" have <F1> prompt for a help topic, rather than displaying the introduction
" page, and have it do this from any mode:
nnoremap <F1> :help<Space>
vmap <F1> <C-C><F1>
omap <F1> <C-C><F1>
map! <F1> <C-C><F1>

"set our filetype to unix
map <F2> :set fileformat=unix<CR>

"toggle line numbers
map <F3> :set number!<CR>

"toggle line wrapping
map <F4> :set wrap!<CR>

"toggle search highlighting
map <F5> :set hlsearch!<CR>

"toggle tag list window
map <F6> :TlistToggle

"Fix common mistypes
abbreviate teh the

"Set up smart indenting for python
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

" Trim trailing whitespace on save
autocmd BufWritePre *.py normal m`:%s/\s\+$//e ``
