

"set nocompatible
set history=100
set undolevels=3000
set noautoindent
set nocindent
set hlsearch
set nostartofline


set ignorecase

set isk+=_,$,@,%,#,- " none of these should be word dividers, so make them not be
set ffs=unix,dos,mac " support all three, in this order

set ruler " Always show current positions along the bottom 
set cmdheight=1 " the command bar is 2 high
set backspace=2 " make backspace work normal

set shortmess=atI " shortens messages to avoid 'press a key' prompt
set noerrorbells " don't make noise
set novisualbell " don't blink

set showmatch " show matching brackets
set mat=3 " how many tenths of a second to blink matching brackets for

set novisualbell " don't blink
set statusline=%F%m%r%h%w\ [FMT=%{&ff}]\ [TYPE=%Y]\ [POS=%04l,%04v][%p%%]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [LEN=%L]
set laststatus=2 " always show the status line

if has("syntax")
   syntax on
endif

"set ai " autoindent
"set si " smartindent 
"set cindent " do c-style indenting
set tabstop=4 " tab spacing (settings below are just to unify it)
set softtabstop=4 " unify
set shiftwidth=4 " unify 
set expandtab " give me spaces please!
"set nowrap " do not wrap lines  

" have <F1> prompt for a help topic, rather than displaying the introduction
" page, and have it do this from any mode:
nnoremap <F1> :help<Space>
vmap <F1> <C-C><F1>
omap <F1> <C-C><F1>
map! <F1> <C-C><F1>

"set our filetype to unix
map <F2> :set fileformat=unix<CR>

"toggle line numbers
map <F3> :set number!<CR>

"toggle line wrapping
map <F4> :set wrap!<CR>

"toggle search highlighting
map <F5> :set hlsearch!<CR>

"Fix common mistypes
abbreviate teh the


